/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queing;

/**
 *
 * @author Daniel
 */
public class Queing_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Queing_GUI
     */
    public Queing_GUI() {
        initComponents();
        jPanelHome.setVisible(true);
        jPanelMap.setVisible(false);
        jPanelCamp.setVisible(false);
        jPanelQuiz.setVisible(false);
        
        /* 
        Lige nu har jeg sat borders til alle panels, for at se hvor store de er, 
        og så det passer med at de er lige store.
        Hvis vi skal ændre i de enkelte panels, kan det nu enkelt gøres ved at 
        bruge designeren, ved at klikke på de enkelte panels i navigatoren.
        */        
 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane = new javax.swing.JLayeredPane();
        jPanelHome = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jPanelCamp = new javax.swing.JPanel();
        jLabelCamp = new javax.swing.JLabel();
        jPanelMap = new javax.swing.JPanel();
        jLabelMap = new javax.swing.JLabel();
        jPanelQuiz = new javax.swing.JPanel();
        jLabelQuiz = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButtonMap = new javax.swing.JButton();
        jButtonCampInfo = new javax.swing.JButton();
        jButtonQuiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roskilde Festival");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(458, 354));

        jPanelHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelHome.setPreferredSize(new java.awt.Dimension(414, 290));

        jLabelHome.setText("Home");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(465, Short.MAX_VALUE)
                .addComponent(jLabelHome))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHome)
                .addContainerGap(586, Short.MAX_VALUE))
        );

        jPanelCamp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCamp.setPreferredSize(new java.awt.Dimension(414, 290));

        jLabelCamp.setText("Camp");

        javax.swing.GroupLayout jPanelCampLayout = new javax.swing.GroupLayout(jPanelCamp);
        jPanelCamp.setLayout(jPanelCampLayout);
        jPanelCampLayout.setHorizontalGroup(
            jPanelCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCampLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabelCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanelCampLayout.setVerticalGroup(
            jPanelCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCampLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelCamp)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        jPanelMap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelMap.setPreferredSize(new java.awt.Dimension(414, 290));

        jLabelMap.setText("MAP");

        javax.swing.GroupLayout jPanelMapLayout = new javax.swing.GroupLayout(jPanelMap);
        jPanelMap.setLayout(jPanelMapLayout);
        jPanelMapLayout.setHorizontalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMapLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabelMap)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanelMapLayout.setVerticalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMapLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelMap)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jPanelQuiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelQuiz.setPreferredSize(new java.awt.Dimension(414, 290));

        jLabelQuiz.setText("Quiz");

        javax.swing.GroupLayout jPanelQuizLayout = new javax.swing.GroupLayout(jPanelQuiz);
        jPanelQuiz.setLayout(jPanelQuizLayout);
        jPanelQuizLayout.setHorizontalGroup(
            jPanelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuizLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabelQuiz)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanelQuizLayout.setVerticalGroup(
            jPanelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuiz)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPaneLayout = new javax.swing.GroupLayout(jLayeredPane);
        jLayeredPane.setLayout(jLayeredPaneLayout);
        jLayeredPaneLayout.setHorizontalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMap, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelCamp, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );
        jLayeredPaneLayout.setVerticalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMap, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelCamp, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneLayout.createSequentialGroup()
                    .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
        );
        jLayeredPane.setLayer(jPanelHome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelCamp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelMap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPanelQuiz, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setLayout(new java.awt.GridLayout());

        jButtonHome.setText("Home");
        jButtonHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonHome.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);

        jButtonMap.setText("Map");
        jButtonMap.setAlignmentY(0.0F);
        jButtonMap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMap.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonMap.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMap);

        jButtonCampInfo.setText("Camp Info");
        jButtonCampInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCampInfo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonCampInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCampInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCampInfo);

        jButtonQuiz.setText("Enter Quiz");
        jButtonQuiz.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonQuiz.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuizActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonQuiz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapActionPerformed
        jPanelHome.setVisible(false);
        jPanelCamp.setVisible(false);
        jPanelQuiz.setVisible(false);
        jPanelMap.setVisible(true);
    }//GEN-LAST:event_jButtonMapActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        jPanelMap.setVisible(false);
        jPanelCamp.setVisible(false);
        jPanelQuiz.setVisible(false);
        jPanelHome.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonCampInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCampInfoActionPerformed
        jPanelMap.setVisible(false);
        jPanelHome.setVisible(false);
        jPanelQuiz.setVisible(false);
        jPanelCamp.setVisible(true);
    }//GEN-LAST:event_jButtonCampInfoActionPerformed

    private void jButtonQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuizActionPerformed
        jPanelMap.setVisible(false);
        jPanelHome.setVisible(false);
        jPanelCamp.setVisible(false);
        jPanelQuiz.setVisible(true);
    }//GEN-LAST:event_jButtonQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Queing_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Queing_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Queing_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Queing_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Queing_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCampInfo;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonMap;
    private javax.swing.JButton jButtonQuiz;
    private javax.swing.JLabel jLabelCamp;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JLabel jLabelQuiz;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCamp;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMap;
    private javax.swing.JPanel jPanelQuiz;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
